# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "centos7" do |centos7|
	  centos7.vm.box = "centos/7"
	  centos7.vm.hostname = "centos7"
	  centos7.disksize.size = "20GB"
	  centos7.vm.network "private_network", ip: "172.16.0.20", virtualbox__intnet: true
	  centos7.vm.provider "virtualbox" do |vb|
		  vb.memory = 1024
	  end
	  centos7.vm.provision "shell", path: "../provision/mysql-setup.sh"
  end
  config.vm.define "ubuntu1804" do |ubuntu1804|
	  ubuntu1804.vm.box = "ubuntu/bionic64"
	  ubuntu1804.vm.hostname = "ubuntu1804"
	  ubuntu1804.disksize.size = "20GB"
	  ubuntu1804.vm.network "forwarded_port", guest: 22, host: 22, auto_correct: true
	  ubuntu1804.vm.network "forwarded_port", guest: 80, host: 80, auto_correct: true
	  ubuntu1804.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
	  ubuntu1804.vm.network "forwarded_port", guest: 443, host: 443, auto_correct: true
	  ubuntu1804.vm.network "forwarded_port", guest: 8443, host: 8443, auto_correct: true
	  ubuntu1804.vm.network "private_network", ip: "172.16.0.10",virtualbox__intnet: true
	  ubuntu1804.vm.provider "virtualbox" do |vb|
		  vb.memory = 1024
	end
    ubuntu1804.vm.provision "shell", path: "../provision/xwiki-setup.sh"
  end

end
